SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
-- --------------------------------------------------------

--
-- Table structure for table `cart`
--
create DATABASE bookstore_db;
use bookstore_db;

CREATE TABLE `cart` (
  `Customer` varchar(40) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `Product` varchar(40) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `Quantity` int(5) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;



--
-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `PID` varchar(25) COLLATE utf8_unicode_ci NOT NULL,
  `Title` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `Author` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `Image` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `MRP` float NOT NULL,
  `Price` float NOT NULL,
  `Discount` int(11) DEFAULT NULL,
  `Available` int(11) NOT NULL,
  `Publisher` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Edition` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Category` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Description` text COLLATE utf8_unicode_ci,
  `Language` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `page` int(5) DEFAULT NULL,
  `weight` int(4) DEFAULT '500'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;



INSERT INTO `products` (`PID`, `Title`, `Author`, `Image`, `MRP`, `Price`, `Discount`, `Available`, `Publisher`, `Edition`, `Category`, `Description`, `Language`, `page`, `weight`) VALUES
('NN1','Ba người lính ngự lâm','Alexandre Dumas cha', 'NN1.jpg','175000','250000','30','5','Văn học','2020','Văn học nước ngoài','Tình cờ gặp gỡ ở Paris, chàng quý tộc tỉnh lẻ d’Artagnan kết thân cùng ba người lính ngự lâm Athos, Aramis, Porthos. Từ bốn con người với những tính cách hoàn toàn khác biệt - nhà quý tộc Athos mẫu mực từ trong ra ngoài, ông hộ pháp Porthos huênh hoang nhưng tốt bụng, ngài “tu viện trưởng” Aramis duyên dáng như con gái nhưng sâu sắc chẳng kém ai, chàng trẻ tuổi d’Artagnan khôn ngoan và liều lĩnh -  họ kết thành một khối thống nhất nhờ tình bạn keo sơn “Một người vì mọi người, mọi người vì một người.” Giữa cảnh tao loạn của nước Pháp thế kỉ XVI, trong thế giới của những ông hoàng bà chúa đầy những âm mưu, thủ đoạn, bốn người bạn cùng nhau bước vào những cuộc phiêu lưu đầy chất anh hùng, nghĩa hiệp nhưng cũng đầy chất lãng mạn của tình yêu. Mời bạn đọc cùng theo bước họ để thấy sống dậy một thời kì lịch sử được soi qua lăng kính kì diệu của trí tưởng tượng mà thêm phần li kì hồi hộp, lại dạt dào cái sôi nổi, hào hứng của tuổi trẻ. ','Tiếng Việt','840','500'),
('NN2','Truyện loài vật',' Ernest Thompson Seton', 'NN2.jpg','84000','120000','30','6',' Văn học','2020','Văn học nước ngoài','Là tác phẩm trong đó lần đầu tiên chim và thú được đưa lên làm nhân vật chính thực sự, Truyện loài vật gồm các câu chuyện cảm động mô tả chân thực, chính xác về hành vi, đời sống của các con vật trong tự nhiên. Đó là Lobo, chúa tể vùng Currumpaw, con sói anh hùng đã chết với sự cô độc kiêu hãnh, không bao giờ màng tới thỏa hiệp. Đó là Chink, chú chó bé nhỏ đã trung thành đến cùng với lời chủ dặn bất chấp cái đói và nỗi sợ. Đó là Johnny, chú gấu con tựa như một đứa trẻ đáng thương...','Tiếng Việt','576','300'),
('NN3','Ngựa ô yêu dấu','Anna Sewell', 'NN3.jpg','56000','80000','30','6','Văn học','2020','Văn học nước ngoài','Được xem là câu chuyện nổi tiếng nhất mọi thời đại về loài vật, Ngựa ô yêu dấu kể lại những cuộc phiêu lưu, những nỗi đắng cay lẫn niềm hạnh phúc của Black Beauty, một chú ngựa ô đẹp mã, trung thành và dũng cảm. Khi bị ông chủ buộc lòng bán đi, Black Beauty phải từ bỏ cuộc sống êm ấm, dễ chịu để bước vào đoạn đời cực nhọc, bị đối xử tàn nhẫn.','Tiếng Việt','292','200'),
('NN4','Con Bim trắng tai đen','Gavriil Troyepolsky', 'NN4.jpg','56000','80000','30','7','Văn học','2020','Văn học nước ngoài','Khi phải lên thành phố chữa bệnh, người thợ săn Ivan Ivanych đã gửi Bim, chú chó thân yêu của mình, cho hàng xóm trông coi. Nhớ chủ đến nối bỏ cả ăn, Bim quyết định ra đi tìm người mà suốt bốn năm chung sống nó chưa bao giờ phải rời xa ấy. Lang thang hết nơi này đến nơi khác giữa mùa đông lạnh giá, Bim trải qua không biết bao nhiêu nỗi vất vả và gian nguy. Bị bắt, bị nhốt và hành hạ đến nỗi chân thì giập nát còn cơ thể ngày càng tàn tạ, suy kiệt song Bim vẫn không thay đổi quyết tâm. Nhưng đến khi người chủ thân yêu gặp được Bim, thì nó đã ra đi mãi mãi. Băng tuyết rơi trên cánh mũi Bim không thể tan ra bởi hơi ấm cơ thể đã không còn.','Tiếng Việt','288','500'),
('NN5','Những tấm lòng cao cả','Edmondo De Amicis', 'NN5.jpg','63000','90000','30','8','Văn học','2020','Văn học nước ngoài','Enrico Bottini, một cậu bé mười tuổi người Ý, trong suốt năm học lớp ba đã đều đặn ghi lại những câu chuyện mà em ấn tượng. Từ những việc làm của thầy cô giáo, bạn bè, hàng xóm cho đến những câu chuyện được đọc trên lớp, những bức thư của mẹ cha hay những sự kiện trên đường phố, tất cả đều được ghi vào một cuốn nhật ký. Với Enrico, mỗi câu chuyện ấy là một bài học về tình thầy trò, bè bạn và cha con… về sự yêu thương, lòng trắc ẩn và tình yêu nước… Tất cả tạo nên một tác phẩm xúc động lòng người.','Tiếng Việt','332','650'),
('NN6','Nanh Trắng','Jack London', 'NN6.jpg','56000','80000','30','9','Văn học','2020','Văn học nước ngoài','Cuối thế kỷ XIX tại Canada, con người đổ xô tìm vàng tại những vùng lạnh giá phương bắc. Được thừa hưởng tất cả những gì tinh túy nhất của sói bố Một mắt và mẹ Kiche, Nanh Trắng sinh ra như để trở thành một chiến binh sói đơn độc với bản năng sinh tồn dẻo dai đến lạ kì trong môi trường khắc nghiệt ấy.','Tiếng Việt','312','400'),
('NN7','Bá tước Monte Cristo','Alexandre Dumas cha', 'NN7.jpg','140000','200000','30','4','Văn học','2020','Văn học nước ngoài','Sắp được giao trọng trách làm một thuyền trưởng, chuẩn bị cưới nàng Mercédès xinh đẹp dịu dàng, có một người cha hết mực thương yêu, được anh em bè bạn mến phục, tương lai của chàng thanh niên Edmond Dantès thật rạng ngời hạnh phúc. Nhưng số mệnh nghiệt ngã, vẽ nên viễn cảnh tươi sáng để rồi bôi đen tất cả. Đúng trong ngày hạnh phúc nhất đời, anh bị bắt giam vào hầm ngục lâu đài If khi chưa đầy hai mươi tuổi bởi âm mưu của những kẻ ghen ghét, đố kị và cơ hội.','Tiếng Việt','642','300'),
('NN8','Thời gian để sống và thời gian để chết','Erich Maria Remarque', 'NN8.jpg','70000','100000','30','2','Đông A','2017','Văn học nước ngoài','','Tiếng Việt','488','290'),
('NN9','Khải hoàn môn','Erich Maria Remarque', 'NN9.jpg','84000','120000','30','3','Đông A','2018','Văn học nước ngoài','Ravic, một bác sĩ tài năng người Đức, đến Paris trong hành trình trốn chạy đế chế Quốc xã tàn bạo. Đã quen với những lần bị truy đuổi, bị bắt giam và bị trục xuất, Ravic vẫn trụ vững được trước những nỗi bất hạnh mà số phận của một người lưu vong đã ném vào anh. Cuộc sống của anh từ lâu chỉ tính bằng ngày, với một mục đích duy nhất: trả thù tên Quốc xã đã hành hạ anh và bức tử người bạn gái của anh khi còn ở Đức. Thế nhưng, cuộc sống, hay chính phép màu từ thành phố của sự lãng mạn, đã mang đến cho anh một niềm an ủi dưới cái tên Joan Madou. Tình yêu với nữ diễn viên xinh đẹp đã một lần nữa gieo vào lòng chàng bác sĩ tài hoa niềm hy vọng về một cuộc sống ấm êm, hạnh phúc giữa những giây phút tăm tối nhất của cuộc đời.','Tiếng Việt','632','500'),
('NN10','Đường về','Erich Maria Remarque', 'NN10.jpg','49000','70000','30','7','Đông A','2017','Văn học nước ngoài','Trở về - là khải hoàn sau những năm chiến chinh, là đoàn tụ sau thời gian xa cách, là khoảnh khắc ấm áp của những con người đã tìm lại được nhau… Nhưng cuộc trở về của những người lính Đức sau Thế chiến I lại là hành trình khắc nghiệt của những cánh chim lạc bầy vật lộn giữa bão giông tìm đường quay lại cố hương, là gánh nặng của lửa đạn chiến tranh chết chóc, là hố thẳm ngăn cách giữa hai phần của cuộc đời. Và cả khi vượt qua tất cả để sang tới bến bờ bên kia, họ cũng chưa chắc sẽ tìm được những gì dấu yêu mình từng để lại sau lưng vào cái năm ly biệt.','Tiếng Việt','328','450'),
('NN11','Bia mộ đen','Erich Maria Remarque', 'NN11.jpg','52500','75000','30','5','Đông A','2019','Văn học nước ngoài','Chơi vơi giữa dòng xoáy cuộc đời khi mà những điều khủng khiếp của chiến tranh vẫn còn ám ảnh, Ludwig Bodmer lựa chọn cách đối mặt bằng thái độ hài hước và bất cần. Tuy nhiên, bên trong anh lại là trái tim của một nhà thơ, với tâm hồn nồng nàn và lãng mạn, đang đấu tranh với thời cuộc và với chính mình để tìm ra ý nghĩa thật sự của cuộc sống mà anh đang và muốn sống.','Tiếng Việt','376','300'),
('NN12','Ba người bạn','Erich Maria Remarque', 'NN12.jpg','77000','110000','30','4','Đông A','2019','Văn học nước ngoài','Với Ba người bạn, nước Đức của Remarque không còn là những tòa nhà màu xám mà là một thành phố nhỏ mờ sương của những bụi tử đinh hương, một góc giáo đường, những quán rượu nhỏ nép mình trong làn mưa lất phất. Đó cũng không phải là đất nước của những bộ óc lạnh lùng lý trí mà là của những thân phận nhỏ bé dù bị trôi giạt đến bước đường cùng vẫn khao khát và chan chứa yêu thương. Đó là một nước Đức của tình cảm và mộng mơ, một nước Đức của nỗi buồn và cái đẹp.','Tiếng Việt','532','200'),
('NN13','Ngụ ngôn La Fontaine','La Fontaine', 'NN13.jpg','935000','1100000','15','3','Văn học','2022','Văn học nước ngoài','Nhà ngôn ngữ học, Nam tước Silvestre de Sacy đã nhận xét: “Ngụ ngôn La Fontaine mang đến niềm hứng khởi cho ba lứa độc giả khác nhau: các em nhỏ hân hoan với sự tươi mới và sinh động của câu chuyện, các sinh viên khoa văn háo hức với nghệ thuật thơ tuyệt diệu, còn người từng trải chìm đắm trong mạch chiêm nghiệm sâu sắc về tính cách và cuộc sống mà ngụ ngôn truyền tải.” Mượn điển tích từ thần thoại Hy Lạp, La Mã và ngụ ngôn của hai nhà hiền triết Ésope và Pilpay, đặt lời thơ vào miệng của những loài vật gần gũi, bằng giọng thơ hóm hỉnh, đôi khi pha chút giọng điệu châm biếm và khéo léo lồng ghép những bài học luân lý, ngụ ngôn La Fontaine đã trở thành món ăn tinh thần cho nhiều thế hệ độc giả.','Tiếng Việt','828','3900'),
('NN14','Hoàng tử bé','Antoine de Saint-Exupéry', 'NN14.jpg','208000','260000','20','5','Đông A','2022','Văn học nước ngoài','Kể về một hoàng tử nhỏ cô đơn từ tiểu tinh cầu xa xôi viếng thăm rồi lại lìa xa Trái Đất, Hoàng tử bé được xem là một trong những tác phẩm thơ mộng nhất của mọi thời đại. Cho đến nay, tác phẩm ra đời vào năm 1943 của nhà văn Saint-Exupéry này đã được dịch sang hơn 300 ngôn ngữ và phát hành hơn 140 triệu bản trên khắp thế giới. Sự giản dị, trong sáng tỏa khắp tác phẩm đã khiến nó trở thành một bài thơ bất hủ mà mãi mãi người ta muốn đem làm quà tặng của tình yêu.','Tiếng Việt','228','800');


INSERT INTO `products` (`PID`, `Title`, `Author`, `Image`, `MRP`, `Price`, `Discount`, `Available`, `Publisher`, `Edition`, `Category`, `Description`, `Language`, `page`, `weight`) VALUES
('LS1','Mahabharata bằng hình - Thiên sử thi vĩ đại nhất của Ấn Độ','DK', 'LS1.jpg','576000','720000','30','5','Dân trí','2020','Lịch sử','Được coi là bộ Vệ Đà thứ 5 trong hệ thống kinh điển Ấn Độ giáo - hệ thống tôn giáo phức tạp và lớn thứ 3 trên thế giới, với cộng đồng khoảng hơn 1,2 tỷ người - Mahabharata truyền tải những chân lý của 4 pho Vệ Đà dưới dạng câu chuyện hấp dẫn. Bộ sử thi này giữ một vị trí quan trọng và còn gây ảnh hưởng đến nhiều mặt trong cả văn hoá nghệ thuật và đời sống ngày nay.','Tiếng Việt','512','600'),
('LS2','Lịch sử thế giới: Chân dung nhân loại theo dòng sự kiện','DK & Viện Smithsonian', 'LS2.jpg','472000','590000','30','6','Dân Trí','2020','Lịch sử','Mở đầu từ sự xuất hiện loài người, cuốn sách đưa bạn qua tiến trình phát triển và suy tàn của các nền văn minh trên toàn thế giới, mà trọng tâm là các sự kiện chiến tranh, thương mại và thám hiểm, các cuộc cách mạng và đổi thay công nghệ… Đặc biệt, nội dung sách không chia theo chủ đề hay khu vực mà được trình bày theo diễn tiến thời gian nhằm giúp bạn có cái nhìn toàn cảnh và so sánh về sự phát triển của các quốc gia, dân tộc tại cùng một thời điểm trong quá khứ.','Tiếng Việt','512','700'),
('LS3','Các nền văn minh thế giới – Combo 5 cuốn Lịch sử cổ đại','Philip Steele, Richard Tames, Fiona Macdonald', 'LS3.jpg','420000','600000','30','7','Dân trí','2018','Lịch sử','Mỗi tập sách sẽ giúp các em quay trở về quá khứ để tìm hiểu những nền văn minh cổ đại: Nhật Bản, Trung Quốc, Ai Cập, Hy Lạp và La Mã. Mỗi tập có hơn 350 tranh ảnh, hình minh họa và bản đồ lịch sử.','Tiếng Việt','456','500'),
('LS4','Danh tướng - Các nhà cầm quân vĩ đại nhất trong lịch sử','R.G.Grant', 'LS4.jpg','400000','500000','30','7','Dân Trí','2019','Lịch sử','Cuốn sách bao gồm thông tin tiểu sử và hình ảnh tướng lãnh, bản đồ trận đánh và chi tiết sống động về các cuộc hành quân. Đây là cẩm nang bằng hình giúp bạn tìm hiểu về các thiên tài quân sự trên thế giới.','Tiếng Việt','360','600'),
('LS5','Những Cuốn Sách Thay Đổi Lịch Sử','Cha Michael Collins cùng với Alexandra Black, Thomas Cussans, John Farndon và Philip Parker', 'LS6.jpg','273000','390000','30','8','Dân Trí','2020','Lịch sử','Những cuốn sách thay đổi lịch sử là một cẩm nang đẹp đẽ và mê hoặc về hơn 80 tác phẩm nổi tiếng, quý hiếm và quan trọng bậc nhất thế giới, từ sử thi Mahābhārata cho đến Kinh Thánh Gutenberg. Mỗi chương sẽ trình bày một cách sinh động về lịch sử ra đời và tầm ảnh hưởng của từng cuốn sách nổi bật được kể tên, dù đó là những bản thảo chép tay trang trí, những tập sách in số lượng lớn hay những ví dụ tiêu biểu nhất của thể loại văn học minh họa.','Tiếng Việt','256','400'),
('LS6','Thiên Tài - Các Nhà Phát Minh Vĩ Đại Và Công Trình Của Họ','Jack Challoner', '.jpg','84000','120000','30','5','Dân Trí','2017','Lịch sử','Thiên Tài - Các Nhà Phát Minh Vĩ Đại Và Công Trình Của Họ là cuốn sách tập hợp 28 thiên tài phát minh nổi tiếng trong lịch sử nhân loại, từ Archimedes, Leonardo da Vinci cho đến James Watt, Thomas Edison... Đó là những con người, với tài năng lỗi lạc, lòng khát khao khám phá vô bờ bến cùng những nỗ lực không mệt mỏi, đã cống hiến cho nhân loại những phát minh vĩ đại làm thay đổi thế giới. Từ bóng đèn điện cho đến truyền hình, máy tính... được giới thiệu một cách sinh động và thú vị trong cuốn sách này.','Tiếng Việt','64','100'),
('LS7','Những người phụ nữ thay đổi thế giới','Kay Woodward', 'LS7.jpg','140000','200000','30','4','Dân Trí','2019','Lịch sử','Dù là những nhà lãnh đạo tài ba trong lịch sử như Cleopatra, Hai Bà Trưng hay Ekaterina Đại đế, hay những nhà khoa học, chính trị gia và nghệ sĩ hiện đại như Marie Curie, Michelle Obama và Emma Watson, thì những người phụ nữ này đều có một điểm chung: họ đã và đang góp phần thay đổi thế giới theo cách riêng của mình.','Tiếng Việt','112','300'),
('LS8','Lịch sử quân sự - Bách khoa thư các loại vũ khí định hình thế giới','DK', 'LS8.jpg','440000','550000','30','6','Dân Trí','2018','Lịch sử','Tập hợp đầy đủ các loại binh khí, máy móc, vật dụng quân sự, từ rìu tay đá lửa thời tiền sử tới vệ tinh do thám và máy bay không người lái ngày nay, Lịch sử Quân sự là bách khoa thư toàn diện về lịch sử không ngừng biến thiên của công nghệ chiến tranh.','Tiếng Việt','448','500');

INSERT INTO `products` (`PID`, `Title`, `Author`, `Image`, `MRP`, `Price`, `Discount`, `Available`, `Publisher`, `Edition`, `Category`, `Description`, `Language`, `page`, `weight`) VALUES
('TN1','Heidi','Johanna Spyri', 'TN1.jpg','156000','240000','35','6','Văn học','2020','Thiếu nhi','Vì vội vã đi kiếm việc làm mới, người dì ích kỉ đã gửi Heidi đến cho ông nội của cô bé, đang sống cô độc trên vùng núi Alm. Ai cũng ái ngại cho Heidi khi phải sống với ông già lập dị và cục cằn ấy. Nhưng ai ngờ được rằng, Heidi bé bỏng với tấm lòng nhân hậu tự nhiên, chẳng những giúp ông nội tìm lại lòng yêu cuộc sống, mà còn mang đến bao đổi thay kì diệu. Những ai từng gặp Heidi, dù ở Dörfli hay Frankfurt, đều muốn cô bé mãi mãi ở bên mình. Nhưng tất cả đều hiểu, chỉ ở giữa cánh đồng hoa rực rỡ, thung lũng mênh mông và ráng chiều rực đỏ trên những ngọn núi thanh tĩnh ngàn đời của dãy Alm, Heidi mới thực sự hạnh phúc để tặng niềm vui cho mọi người.','Tiếng Việt','304','200'),
('TN2','Peter Pan',' J. M. Barrie', 'TN2.jpg','280000','350000','20','7','Đông A','2020','Thiếu nhi','Peter Pan sống ở Neverland, hòn đảo xinh đẹp, sống động nhưng cũng đầy bí ẩn dưới sương mù của trí nhớ và mộng mơ. Ở Neverland, lũ trẻ đi lạc chung sống với những cô cậu tiên bé xíu, với thổ dân da đỏ, dã thú, tiên cá và cả hải tặc. Ở đó thời gian dường như đứng im, chỉ có những cuộc rượt bắt cứ xoay vòng, xoay vòng.','Tiếng Việt','263','300'),
('TN3','Mười vạn câu hỏi vì sao?','Nguyễn Bá Cao', 'TN3.jpg','256000','320000','20','3','Dân trí','2020','Thiếu nhi','Tuổi thơ là khoảng thời gian đẹp nhất trong cuộc đời mỗi con người. Ở lứa tuổi này, trẻ luôn tràn trề hy vọng, cùng những ngây thơ trong sáng buổi ban đầu. Đứng trước thế giới với bao điều kỳ diệu mang trong mình sự tò mò, khát vọng tìm hiểu, câu nói thường thấy nhất ở trẻ là "Vì sao?" Để có thể trả lời chính xác câu hỏi của trẻ, không phải là việc đơn giản. Các nghiên cứu cho thấy, sự phát triển ở bộ não trẻ diễn ra nhanh nhất trong 13 năm đầu đời. Là một phụ huynh, khi không mang lại cho trẻ cơ hội suy nghĩ, tìm hiểu, có thể bạn sẽ phải hối tiếc! Thế giới ngày nay phát triển nhanh chóng, kho tàng kiến thức là vô hạn, luôn được đổi mới với tốc độ chóng mặt. Cũng xuất phát từ những suy nghĩ trên, chúng tôi đã thu thập rộng rãi, lựa chọn kĩ càng các câu hỏi mà các em nhỏ cảm thấy hứng thú để đưa ra bộ sách Mười vạn câu hỏi vì sao?, mang lại cho các em những câu trả lời theo từng chủ đề. Cuốn sách, với sự đóng góp của các chuyên gia khoa học thường thức giàu kinh nghiệm, sử dụng ngôn ngữ dễ hiểu, kết hợp những hình ảnh minh họa sinh động sẽ mang đến cho các em những kiến thức cơ bản, chứa đựng nội dung phong phú, xoay quanh nhiều chủ đề hấp dẫn:','Tiếng Việt','328','400'),
('TN4','Động Vật: Bách khoa thư hình ảnh về các loài vật trên trái đất','DK', 'TN4.jpg','7000','10000','30','6','Đông A','2020','Thiếu nhi','Động vật – Bách khoa thư hình ảnh về các loài vật trên Trái Đất bao gồm vô vàn thông tin và hình ảnh về những sinh vật tuyệt vời đang cư ngụ trên hành tinh xanh chúng ta, từ thực vật đến động vật, từ dưới đáy biển sâu đến trên đỉnh núi cao, từ loài vi khuẩn nhỏ bé đến loài voi khổng lồ. Với thông tin thú vị và dễ hiểu về hơn 1.500 loài, đây là cẩm nang thiết yếu cho các “nhà tự nhiên học tương lai” vừa học vừa chơi, vừa tìm hiểu những kiến thức bổ ích vừa thư giãn với những tranh ảnh tuyệt đẹp.','Tiếng Việt','304','500'),
('TN5','21 Chuyện Cướp Biển','Nhiều tác giả', 'TN5.jpg','90000','150000','40','4','Dân Trí','2020','Thiếu nhi','21 chuyện cướp biển là cuốn sách tập hợp những câu chuyện vui vẻ, hài hước về nghề cướp biển. Đó là câu chuyện thú vị về bé Titu đi tìm kiếm kho báu theo tấm bản đồ nhặt được trên bờ biển. Nhưng cuối cùng, kho báu hấp dẫn cậu nhất là những vỏ sò đầy màu sắc mà cậu dự định sẽ xâu thành chiếc vòng cổ dành tặng mẹ yêu. Còn chuyện Cướp biển tìm vàng kể về chuyến ra đảo tìm vàng của hai anh em Victor và Lili. Cuối cùng, kho báu hai anh em tìm được chỉ là một đồng bạc, nhưng chỉ thế cũng đã khiến hai em rất vui rồi. Ngoài những câu chuyện kể về các em nhỏ hào hứng đóng vai cướp biển, cuốn sách còn có những mẩu chuyện về những cướp biển thực thụ. Đó là cô con gái của cướp biển Nadan Hung Hãn nhanh trí, dũng cảm hay anh chàng Trojenti có tài bắn đại bác… Và thêm rất nhiều câu chuyện vui về cô gà Út đẻ trứng vàng trên thuyền; chú cừu Habib luôn mơ ước tìm được kho báu chôn trên đảo hay những tên cướp biển nổi tiếng thi nấu ăn chỉ vì muốn được ở bên cô công chúa Florida xinh đẹp…','Tiếng Việt','112','300'),
('TN6','Theo Dấu Chân Loài Vật - Cáo Con','Pierre Couronne', 'TN6.jpg','5000','6500','20','7','Đông A','2020','Thiếu nhi','Thiên nhiên luôn ẩn chứa bao điều thú vị chờ ta khám phá. Một lần nữa, bộ sách Theo dấu chân loài vật do hai tác giả nổi tiếng Pierre Couronne minh họa, Alain Jost viết lời và nhà văn Châu Diên dịch sẽ giúp các bạn nhỏ phiêu lưu vào thế giới diệu kỳ ấy qua 12 tập sách kể về 12 câu chuyện của các con vật khác nhau. Trên thảo nguyên bao la đầy nắng và gió, các em có thể nô đùa cùng Ngựa nhỏ, Sư tử bé và Voi con. Trong rừng thẳm hoang sơ, các em sẽ được hồi hộp dõi theo cuộc sống đầy biến động của Hươu con, Cáo con và Gấu. Còn tới khu nông trại thanh bình, tươi đẹp, các em sẽ vô cùng hào hứng cùng tham gia vào các trò nghịch ngợm của mèo Pilou, dê Hạt Dẻ và chó Axel. Những cuộc gặp gỡ kỳ thú, những lần trốn chạy thót tim hay các trò đùa láu lỉnh, tất cả vừa mới lạ, lại vừa rất thân quen tựa như bước ra từ chính cuộc sống hàng ngày của các bạn nhỏ vậy.','Tiếng Việt','30','200'),
('TN7','Truyện cổ Anđécxen','H.C. Andersen', 'TN7.jpg','88200','126000','30','4','Đông A','2020','Thiếu nhi','Truyện cổ tích Anđécxen từ lâu đã quen thuộc với các bạn nhỏ trên khắp thế giới. Những câu chuyện cổ gợi mở trí tưởng tượng, sự hiểu biết của các em về thế giới xung quanh. Hơn thế nữa, truyện cổ tích Anđécxen giáo dục các em lòng yêu thương, biết ơn và kính trọng đối với ông bà, cha mẹ… Ngay cả người lớn, khi đọc cũng cảm nhận được những điều thú vị và bổ ích qua các câu chuyện nhỏ đáng yêu.','Tiếng Việt','687','300'),
('TN8','365 chuyện kể hằng đêm','NXB Bắc Kinh', 'TN8.jpg','68800','86000','35','6','NXB Bắc Kinh','2020','Thiếu nhi','Trẻ nhỏ thường nhận thức thế giới qua những điều đơn giản. Chính vì thế những quan điểm chuẩn mực về đạo đức của mỗi người thường bắt nguồn từ những câu chuyện nghe kể từ thuở ấu thơ. Và không biết tự bao giờ hạt giống ấy nảy mầm trong lòng các em, để này mai này khôn lớn, dẫu có đọc thêm rất nhiều sách vở, biết thêm rất nhiều kiến thức nhưng câu chuyện ngày xưa vẫn in dấu đậm sâu.','Tiếng Việt','364','400');

INSERT INTO `products` (`PID`, `Title`, `Author`, `Image`, `MRP`, `Price`, `Discount`, `Available`, `Publisher`, `Edition`, `Category`, `Description`, `Language`, `page`, `weight`) VALUES
('VN1','Bỉ vỏ','Nguyên Hồng', 'VN1.jpg','272000','320000','15','5','Văn học','2019','Văn học Việt Nam','Tiểu thuyết Bỉ vỏ được Nguyên Hồng viết đi viết lại ít nhất năm lần, hoàn thành vào ngày 26 tháng 4 năm 1937 và giành được giải thưởng văn chương của Tự Lực Văn Đoàn. Lúc đó, nhà văn mới mười chín tuổi. Ở cái tuổi còn non nớt nhưng đã chịu nhiều ghẻ lạnh và sớm sống đời bươn chải, Nguyên Hồng khi ấy vào tù ra tội và tiếp xúc với mọi hạng người cùng khổ trong xã hội. Chính trải nghiệm đã cung cấp những chất liệu đầu tiên cho sáng tác của ông.','Tiếng Việt','256','500'),
('VN2','Thương nhớ mười hai','Vũ Bằng', 'VN2.jpg','297500','350000','15','2','Văn học','2019','Văn học Việt Nam','Trong Thương nhớ mười hai, Vũ Bằng viết về “mười hai cuộc đổi thay tiết trời, mười hai sự rung động uyển chuyển của năm tháng, của chim muông, của sắc đẹp, của hoa lá, của thương yêu, tình tứ” (Tự ngôn). Không chỉ đầy ắp những cảnh, những tình đắm đuối thiết tha, không chỉ duyên dáng và ý nhị kể biết bao câu chuyện về ẩm thực, thú vui, phong tục của miền Bắc, tùy bút này còn là một điển hình cho phong cách Vũ Bằng, đặc biệt với việc sử dụng câu từ tiếng Việt trong sáng, uyển chuyển, đầy nhạc tính. Một tùy bút đẹp như mơ. Mà đúng là giấc mơ.','Tiếng Việt','300','400'),
('VN3','Người kép già','Kim Lân', 'VN3.jpg','288000','360000','20','4','Văn học','2020','Văn học Việt Nam','Người kép già bao gồm những truyện ngắn và vừa của nhà văn Kim Lân mà tôi đã đọc những truyện này và có truyện đọc rất nhiều lần. Nhưng ấn bản lần này vẫn làm tôi ngập tràn cảm hứng và chìm sâu trong suy tưởng khi đọc lại. […] Những tác phẩm trong cuốn sách này của ông là những câu chuyện đời sống của gần một thế kỷ trước. Nhưng tất cả vẫn như vừa diễn ra. Ngôn ngữ và những thông điệp chứa đựng bên trong những câu chuyện của ông vẫn rực ấm như một dòng máu chảy trong cơ thể thời gian mà những người đương thời đang sống trong đó. Mọi hình thức xã hội luôn thay đổi nhưng bản chất của kiếp người không thay đổi, mọi ngôn ngữ có thể thay đổi nhưng bản chất của tình yêu thương con người và cái Thiện không hề thay đổi. Văn chương của nhà văn Kim Lân thuộc về những điều không thể thay đổi ấy. Ông đã chạm vào cái lõi của kiếp nhân sinh và ông cũng sống trong cái lõi của mọi kiếp nhân sinh vì vậy ông còn mãi đến bây giờ.','Tiếng Việt','340','450'),
('VN4','Số Đỏ','Vũ Trọng Phụng', 'VN4.jpg','256000','320000','20','5','Văn học','2018','Văn học Việt Nam','Số đỏ là một trong những tiểu thuyết làm nên tên tuổi của nhà văn Vũ Trọng Phụng. Tác phẩm xoay quanh cuộc đời của nhân vật chính Xuân Tóc Đỏ, từ khi hắn là một kẻ hạ lưu bỗng chốc đổi đời, nhảy lên tầng lớp danh giá của xã hội nhờ trào lưu Âu hóa của giới tiểu tư sản Hà Nội khi đó.','Tiếng Việt','280','330'),
('VN5','Truyện Ngắn Nguyễn Huy Thiệp','Nguyễn Huy Thiệp', 'VN5.jpg','360000','450000','20','7','Văn học','2017','Văn học Việt Nam','Truyện ngắn Nguyễn Huy Thiệp (Với minh họa của các họa sĩ) được in lại theo bản năm 2007 cũng do Đông A xuất bản, nhân kỷ niệm 70 năm ngày sinh tác giả (1950 - 2020). Các truyện trong sách do chính nhà văn tuyển lựa, sắp xếp theo thứ tự thời gian. Trong bản in năm 2007, nhà văn Nguyễn Huy Thiệp đã liên tài, mời nhiều họa sĩ đương đại vẽ minh họa cho tập sách. Trong bản in mới năm 2020, bạn đọc sẽ gặp lại đa phần minh họa của các họa sĩ đương đại Việt Nam. Ngoài ra, để làm mới cuốn sách, chúng tôi quyết định mời thêm một số họa sĩ vẽ minh họa mới cho các truyện ngắn vốn rất nổi tiếng của nhà văn Nguyễn Huy Thiệp, đồng thời lược bỏ một vài minh họa trong bản in trước.  ','Tiếng Việt','569','340'),
('VN6','Đảo mộng mơ','Nguyễn Nhật Ánh', 'VN6.jpg','160000','200000','20','4','Văn học','2020','Văn học Việt Nam','Đảo mộng mơ là một lát cắt đời sống của những đứa trẻ lên 10 giàu trí tưởng tượng như tất cả mọi đứa trẻ. Chúng mơ mộng, tưởng tượng, và tự làm “hiện thực hóa” những khao khát của mình.','Tiếng Việt',' 220 ','440'),
('VN7','Lục Vân Tiên','Nguyễn Đình Chiểu', 'VN7.jpg','117500','235000','50','8','Văn học','2019','Văn học Việt Nam','Ấn phẩm lần này được in cùng với 18 tranh minh họa của họa sĩ Nguyễn Công Hoan.','Tiếng Việt','176','120'),
('VN8','Truyện Cổ Tích Việt Nam','Nguyễn Cừ', 'VN8.jpg','139300','199000','30','4','Văn học','2019','Văn học Việt Nam','Kho tàng truyện cổ tích Việt Nam vô cùng phong phú và đa dạng, đã được giới thiệu tới bạn đọc thông qua nhiều tuyển tập khác nhau. Nhằm giới thiệu đến bạn đọc những những truyện cổ tích hay nhất, Đông A tiếp tục tái bản Truyện cổ tích Việt Nam do Nguyễn Cừ tuyển chọn. Tuyển tập gồm những truyện hay, tiêu biểu đủ các dân tộc, đủ các thể tài cổ tích. Người tuyển chọn cũng đã cân nhắc sao cho cho tỷ lệ truyện giữa các dân tộc có một sự hợp lý, tránh những truyện trùng lặp, truyện lai căng áp đặt vào dân tộc mình.','Tiếng Việt','712','700');

INSERT INTO `products` (`PID`, `Title`, `Author`, `Image`, `MRP`, `Price`, `Discount`, `Available`, `Publisher`, `Edition`, `Category`, `Description`, `Language`, `page`, `weight`) VALUES
('VNN1','Bên Kia Sông','Phùng Văn Khai', 'VNN1.jpg','120000','150000','20','5','Hội Nhà Văn','2022','Việt Nam đương đại','Truyện ngắn khó - dễ, thành - bại nằm ở đường tơ kẽ tóc mà giọng văn đôi khi cũng có tính quyết định của nó. Lại đến mươi năm tôi ít viết truyện ngắn, lùi lại, nhẩm đọc những truyện đã viết của mình, thấy nhiều cái cũng sơ sài, ọp ẹp. Được vài cái trụ được chẳng qua là có cốt truyện vững mà thôi. Mới thấy đời văn thăm thẳm, càng đi càng thấy phía trước hút hắt, vô định. Nhưng rất đẹp. Đẹp trong sự bi tráng của cuộc sống lẫm liệt luôn dẫn dụ ngòi bút...','Tiếng Việt','288','200'),
('VNN2','Nắng Thổ Tang','Đinh Phương', 'VNN2.jpg','120000','150000','20','6','Hội Nhà Văn','2022','Việt Nam đương đại','NẮNG THỔ TANG mở đầu bằng cái chết của các chí sĩ Yên Bái. Đinh Phương mở màn cuốn tiểu thuyết đầy tham vọng của mình bằng lời kể của một đao phủ. Lần này kẻ ban phát cái chết đóng vai người hồi sinh hàng loạt cái tên đã khuất lấp trong trầm tích lịch sử. Những cái tên gắn liền với Việt Nam Quốc Dân Đảng của Nguyễn Thái Học chìm nổi giữa dòng chảy song song của thời gian, giữa hư và thực, giữa những lời thì thầm và cả những tiếng thét đau thương. Người tuần đường đếm những thanh ray, ả lơ xe trên những lộ trình liên tỉnh, cô phóng viên truy lùng một cái tên quá khứ, và gã thanh niên mơ hồ theo dấu con ngựa trắng để hoàn hương. Họ đi, và đã đi, như hàng nghìn phận người khốn khổ từng bỏ xứ mà đi thời năm tư biến loạn. Ai ăn năn? Ai vô tội? Ai giết người? Ai dối Chúa? Các nhân vật sẽ phải tự tìm câu trả lời cho chính họ trước khi câu hỏi bị lấp đi dưới cát thời gian, hay ám ảnh hơn, khi mọi thứ đều tan ra trong nắng.','Tiếng Việt','310','400'),
('VNN3','Một Ví Dụ Xoàng','Nguyễn Bình Phương', 'VNN3.jpg','120000','150000','20','5','Hội Nhà Văn','2022','Việt Nam đương đại','Với tiểu thuyết Một ví dụ xoàng, nhà văn Nguyễn Bình Phương đã đưa bạn đọc đến một vụ án gấy chấn động vùng trung du những ngày tháng cũ, cùng những phận người đang loay hoay trong cối xay thời cuộc.','Tiếng Việt','206','200'),
('VNN4','Và Khi Tro Bụi','Đoàn Minh Phượng', 'VNN4.jpg','78400','98000','20','4','Hội Nhà Văn','2022','Việt Nam đương đại','TÔI VẪN NHỚ những thời khi tình yêu vẫn còn đó. Khi tôi nghe tiếng chim gọi nhau những chiều tối, hay tiếng còi của những con tàu chở than trên sông Rhein đi ngang qua thành phố, tôi tìm được chút ý nghĩa trong những âm thanh quen thuộc buồn buồn của một ngày. Hoặc khi tôi đi làm về nhà vào một chiều thu, bước vào một căn phòng chưa thắp đèn, nhìn thấy chút nắng cuối ngày hắt qua cửa sổ và rọi qua cái ly nước bằng thủy tinh uống dở còn để trên bàn, tôi tìm được cái đẹp trong cái ánh sáng mong manh đó. Những đồ vật và những khoảnh khắc của cuộc đời được gắn lại với nhau bằng một thứ keo, nối lại với nhau bằng chút ý nghĩa, một chút tình yêu, khẽ khàng và ít đam mê, nhưng bàng bạc đủ để cho cuộc đời được nguyên vẹn.','Tiếng Việt','175','300'),
('VNN5','Tiếng Kiều Đồng Vọng','Đoàn Minh Phượng', 'VNN5.jpg','78400','98000','20','7','Hội Nhà Văn','2020','Việt Nam đương đại','TIẾNG KIỀU ĐỒNG VỌNG là hành trình tìm lại bản ngã của một cô gái trẻ luôn bị mắc kẹt trong những câu hỏi thuộc về quá khứ. Có lẽ, khi người ta bắt đầu học cách đưa ra câu trả lời cho những nghi vấn trớ trêu mà số phận đặt ra, dù tiếng vọng cuối cùng chưa hẳn là một đáp án tiệm cận nhất với sự thật thì rốt cuộc, ta cũng dần tiến đến sự trưởng thành bản ngã - thời khắc cái tôi cá nhân phải tự phá vỡ vỏ trứng bảo bọc an toàn tưởng chừng vững chắc như một thành trì nhưng hóa ra lại chỉ mong manh như một làn sương dệt từ những mơ hồ bất quyết. Chỉ khi thành trì ấy sụp đổ, làn sương ấy lùi lại phía sau con người vừa bước ra từ sự tổn thương, chính khi ấy ta mới có thể nhìn rõ hơn thế giới với trọn vẹn hương sắc của nó.','Tiếng Việt','244','200'),
('VNN6','Đốt cỏ ngày đồng','Đoàn Minh Phượng', 'VNN6.jpg','78400','98000','20','7','Hội Nhà Văn','2020','Việt Nam đương đại','NGÀY NÀO CÒN mang thân người, ngày ấy người ta còn có thể bị ức hiếp, đày đọa, cách chia.  Không còn thân người, sẽ không còn thân phận. Tự do chỉ có thể tìm được khi chúng tôi đã bỏ đi cái thân xác biết đau đớn, quẫn bách, đói khát, tuyệt vọng, mong mỏi. Và nếu người ta chết đi không còn linh hồn, thì chúng tôi chết đi sẽ còn lại một ý niệm, tựa như là một tứ thơ. Không ai biết đến nó, đứng bên ngoài cân nhắc của loài người, tứ thơ ấy nguyên vẹn biết là bao. Người ta sống, và chết, vì một mục đích, một niềm tin nào đó, họ đem thân mình và cuộc đời mình để làm hiển thị một ý niệm, tại sao chúng tôi không sống, và rồi chết đi cho một tứ thơ của riêng chúng tôi thôi, duy nhất và nguyên vẹn, dù tứ thơ ấy không thể viết nên lời: nó là tiếng thở của thinh không.','Tiếng Việt','172','340'),
('VNN7','Muôn Dặm Sầu Giăng','Võ Diệu Thanh', 'VNN7.jpg','96000','120000','20','8','Hội Nhà Văn','2020','Việt Nam đương đại','Lương tâm tôi trong sạch. Câu nói ấy của Pol Pot đã khiến Võ Diệu Thanh lên đường và trở về Ba Chúc, vùng đất không thôi ám ảnh những suy nghĩ của chị. Không còn là một trận thảm sát hàng loạt với những đống xương không tên tuổi, Võ Diệu Thanh đã để cho từng người ở lại có cơ hội hiện diện với những sáng tối của chính họ để cùng đối diện với những câu hỏi chưa từng có lời giải đáp. Tại sao con người có thể phi nhân với con người? Tại sao cái ác không ngừng nhân danh một điều gì đó tốt đẹp? Và hơn hết, tại sao lại là Ba Chúc?','Tiếng Việt','300','340'),
('VNN8','Thời tái chế','Mai Văn Phấn', 'VNN8.jpg','88000','110000','20','9','Hội Nhà Văn','2020','Việt Nam đương đại','Mai Văn Phấn được xem là gương mặt thơ ca tiêu biểu của Việt Nam trong 20 năm qua bởi những nỗ lực cách tân không mệt mỏi. Ông là nhà thơ có ý thức học hỏi những nền thơ ca hiện đại đi trước, sẵn sàng thu nạp kỹ thuật của các trường phái, triết thuyết để thử nghiệm làm mới, làm khác biệt tác phẩm của mình. Thơ ông nghiêng về lý trí, điêu luyện về dùng chữ, tân kỳ trong áp dụng các kỹ thuật trường phái thơ ca khác nhau; xử lý hài hòa giữa thành tựu thơ ca truyền thống và sự cách tân hiện đại. Mai Văn Phấn đang hướng đến một giọng thơ dựa trên thẩm mỹ quan cá nhân độc lập. Cảm quan thơ ca của ông chỉ ra tính bất khả xâm phạm của đời sống.','Tiếng Việt','80','230');

INSERT INTO `products` (`PID`, `Title`, `Author`, `Image`, `MRP`, `Price`, `Discount`, `Available`, `Publisher`, `Edition`, `Category`, `Description`, `Language`, `page`, `weight`) VALUES
('J1','Từ Dạo Ấy','Natsume Soseki', 'J1.jpg','188000','235000','20','5','Hội Nhà Văn','2020','Văn học Nhật','TỪ DẠO ẤY được xếp hạng là một trong những tiểu thuyết sâu sắc và gây xúc động nhất của Natsume Soseki. Câu chuyện được kể trong bối cảnh đất nước Nhật Bản sau thời kỳ chuyển giao giữa chế độ Mạc phủ và Duy Tân Minh Trị, khi văn minh của Tây phương đang len lỏi vào từng ngõ ngách trong đời sống. Daisuke - cậu ấm vô dụng của một gia đình giàu có, được học hành đàng hoàng, nhưng sau khi tốt nghiệp thì không chịu đi làm, vẫn ăn bám gia đình. Bước qua tuổi ba mươi, Daisuke không sự nghiệp, không vợ con, cuộc sống của anh là dành trọn thời gian cho việc lang thang vô định cùng những thú vui phù phiếm, anh thờ ơ với hết thảy, cho tới khi anh gặp lại người bạn thân thời đại học và tình yêu đầu đời của mình, Daisuke buộc phải thực hiện công cuộc tìm kiếm bản thân một cách rốt ráo... Bi kịch của Daisuke không chỉ là sự giằng xé giữa hèn nhát và dũng cảm, giữa tự do cá nhân và trách nhiệm xã hội, mà còn là cuộc đối chọi giữa lề lối tập tục cổ xưa và lý tưởng văn minh tân tiến.','Tiếng Việt','408','200'),
('J2','Truyện tối trăng mưa','Ueda Akinari', 'J2.jpg','120000','150000','20','6','Hội Nhà Văn','2020','Văn học Nhật','Truyện tối trăng mưa là tập truyện truyền kỳ kết hợp nhuần nhuyễn hai nguồn Hán-Hòa, vừa thực tiễn, vừa lãng mạn, được nhiều thế hệ độc giả Nhật Bản yêu mến và có ảnh hưởng đến lối viết của tiểu thuyết cận đại. Trong tập truyện này, Ueda Akinari không chỉ vẽ nên bức tranh phong cảnh Nhật Bản thơ mộng qua những đoạn văn đi đường - Michiyukibun, mà ông còn huy động cả văn hóa truyền thống dân tộc của xứ sở Mặt Trời mọc, từ Vạn diệp tập, thơ Waka thập bát đại tập, thơ Haikai, không những lịch sử Trung Quốc mà cả lịch sử Nhật Bản, cũng như thành ngữ, phong tục dân gian. Lúc đùa cợt, lúc nghiêm trang, khi mỉa mai, khi cay đắng, Akinari đã đưa độc giả vào một thế giới u linh đặc sắc, mờ mờ ảo ảo của những đêm trăng sau cơn mưa...','Tiếng Việt','268','300'),
('J3','Mong Manh Hoa Tuyết - Quyển Hạ','Tanizaki Junichiro', 'J3.jpg','112000','140000','20','4','Hội Nhà Văn','2020','Văn học Nhật','Trong hơi nóng của Thế chiến II, những nỗ lực níu kéo nếp sống phù hoa thơ mộng của chị em nhà Makioka, hậu duệ của một danh gia bên bờ tàn lụi, bỗng trở nên mong manh như hoa tuyết... Tao ngộ của họ tiêu biểu cho những xung đột thế hệ điển hình của xã hội Á Đông, và đặc biệt là cho thân phận người phụ nữ ở thời điểm chuyển giao lịch sử. Bốn cô gái nhà Makioka một mặt đều là sản phẩm trực tiếp của thời đại, mặt khác vẫn là bốn cá tính hấp dẫn và khác biệt trong cách mỗi người đương đầu với những đổi thay của thời cuộc. Yếu đuối nhưng cũng rất kiên cường trước mọi phũ phàng của bi kịch gia đình và của cuộc loạn ly sắp sửa, họ vẫn xứng đáng là sứ giả của cái đẹp, dẫu chỉ là chút dư quang sót lại của ngày tàn.','Tiếng Việt','324','300'),
('J4','Mong Manh Hoa Tuyết - Quyển trung','Tanizaki Junichiro', 'J4.jpg','104000','130000','20','7','Hội Nhà Văn','2020','Văn học Nhật','ĐẤT NƯỚC NHẬT BẢN vào thời của Tanizaki hẳn đã khác xa so với Nhật Bản thời nay, nhưng tác phẩm của ông vẫn luôn đóng vai trò như những nghiên cứu sắc bén về một nền văn hóa thường trực biến đổi, về những thách thức đến từ công cuộc giao hòa giữa truyền thống và hiện đại. Bên cạnh việc mô tả một đất nước Nhật Bản đa chiều tiến hóa, Tanizaki còn tập trung khắc họa đời sống gia đình của từng nhân vật để thông qua đó vượt thoát những quy chuẩn hà khắc vốn chi phối hành vi xã hội, làm bộc lộ đời sống nội tâm sôi sục khi họ thích nghi hay chống cự với hoàn cảnh. Tuy lấy bối cảnh ở những nơi chốn cụ thể, nhưng tâm tư và tình cảm phóng khoáng của nhân vật chính là điều giúp cho tác phẩm của Tanizaki xuyên vượt chiều kích không gian, và cả thời gian','Tiếng Việt','288','300'),
('J5','Mong manh hoa tuyết - quyển thượng','Tanizaki Junichiro', 'J5.jpg','96000','120000','20','3','Hội Nhà Văn','2020','Văn học Nhật','MONG MANH HOA TUYẾT là trường thiên tiểu thuyết của Tanizaki Junichirō về đất nước Nhật Bản nhiều tâm tư và xung đột ý thức hệ trước công cuộc canh tân của kỷ nguyên mới. Câu chuyện xoay quanh sự thoái trào của nhà Makioka - một danh gia vọng tộc ở Osaka vào đầu thế kỷ 20, nơi những phong tục truyền thống trên đà tan rã, nơi văn hóa Tây dương len lỏi vào từng tập quán gia đình. Bốn chị em gái nhà Makioka - người đại diện cho quá khứ - người đại diện cho tương lai - một mặt luôn đau đáu về cái danh quá vãng của dòng tộc, mặt khác buộc phải vật lộn để thích nghi với thời cuộc mới...','Tiếng Việt','236','200'),
('J6','Chết giữa mùa hè','Yukio Mishima', 'J6.jpg','188000','235000','20','5','Hội Nhà Văn','2020','Văn học Nhật','CHẾT GIỮA MÙA HÈ là tập truyện kết tinh những lý tưởng sống cốt lõi cùng những góc khuất ẩn ức thậm sâu trong con người Yukio Mishima. Đó là sự ngợi ca và nỗi ám ảnh thường trực dành cho cái chết, là tiếng khóc hoan lạc và bi ai của những tâm hồn đang yêu muốn được giải phóng khỏi sự hạn hẹp của giới tính và xác thịt, là nỗi cô đơn vĩnh cửu của nhân loại lúc bình sinh...','Tiếng Việt','326','400'),
('J7','Matasaburo - Từ phương của gió','Kenji Miyazawa', 'J7.jpg','49600','62000','20','5','Hội Nhà Văn','2020','Văn học Nhật','KÌ NGHỈ HÈ kết thúc, lớp học nơi làng nhỏ bỗng xôn xao bởi sự xuất hiện của một cậu nhóc mái tóc đỏ kỳ dị không biết từ phương nào tới. Những đứa nhỏ trong lớp ngờ rằng nhân vật bí hiểm mới tới này chính là Matasaburo - hiện thân của gió. Cậu nhóc rốt cuộc là ai? Cậu sẽ mang tới ngọn gió mới nào cho ngôi làng nhỏ bên sông? Với những hình ảnh thi vị, những xúc cảm trong sáng, Kenji Miyazawa đã mang đến cho độc giả một câu chuyện đẹp về tình bạn trẻ thơ...','Tiếng Việt','104','300'),
('J8','Tuyển tập Mori Ogai','Mori Ogai', 'J8.jpg','188000','235000','20','9','Hội Nhà Văn','2020','Văn học Nhật','Chưa có thời kỳ nào trong lịch sử xã hội Nhật Bản hiện đại lại hỗn loạn và đầy kịch tính như thời kỳ Minh Trị. Và cũng không có một nhà văn nào có thể vẽ nên một bức tranh thời đại Minh Trị thành công như Mori Ogai. Ông đã kết hợp một cách hài hòa lối hành văn mới mẻ của Tây phương với văn hóa truyền thống lâu đời Nhật Bản; cùng bút pháp thanh nhã, triết lý sâu xa, vốn kiến thức cực kỳ phong phú, khả năng sử dụng Hán văn điêu luyện, Mori Ogai không những đã đưa được tinh thần khai sáng, thổi một luồng gió mới vào văn đàn, mà còn lột tả được bản chất hỗn độn và cái nhìn nhuốm màu hoài niệm trong giai đoạn chuyển giao một cách ưu nhã','Tiếng Việt','330','200');

INSERT INTO `products` (`PID`, `Title`, `Author`, `Image`, `MRP`, `Price`, `Discount`, `Available`, `Publisher`, `Edition`, `Category`, `Description`, `Language`, `page`, `weight`) VALUES
('HK1','TA BA LÔ TRÊN ĐẤT Á','Rosie Nguyễn', 'HK1.jpg','86000','86000','0','5','Nhã Nam','2020','Hồi ký/tự truyện','Quyển sách đầu tiên của Rosie Nguyễn, nay trở lại với một diện mạo mới và một quốc gia mới mà trước đây tác giả chưa có dịp nhắc đến. Ta ba lô trên đất Á không chỉ là cẩm nang du lịch bụi dành cho những ai yêu thích khám phá Đông Nam Á, mà còn là dấu ấn rất riêng của Rosie Nguyễn khi một mình đeo ba lô, tay cầm bản đồ ngược xuôi khắp các nước láng giềng để đi tìm chính mình và theo đuổi đam mê.','Tiếng Việt','412','200'),
('HK2','NAM VÀ SYLVIE','Phạm Duy Khiêm', 'HK2.jpg','60000','60000','0','3','Nhã Nam','2020','Hồi ký/tự truyện','','Tiếng Việt','60','70'),
('HK3','41 NĂM LÀM BÁO','Hồ Hữu Tường', 'HK3.jpg','52000','52000','0','4','Nhã Nam','2020','Hồi ký/tự truyện','41 năm làm báo không chỉ là câu chuyện đời chuyện nghề của một ký giả miền Nam lão thành mà cuộc đời gắn chặt cùng nhiều biến động của dân tộc, mỗi trang sách còn là một thước phim tài liệu sống động, đôi chỗ hài hước nhưng chân thực về cuộc đời viết sách, làm báo, làm chính trị của Hồ Hữu Tường và những đồng chí cùng thời với ông: Nguyễn An Ninh, Phan Văn Hùm, Tạ Thu Thâu – những con người thuộc một thế hệ trẻ trung, phóng khoáng,dấn thân, không chọn vinh thân phì gia mà coi cách mạng là con đường tất yếu của cuộc đời mình trong thời mất nước.','Tiếng Việt','224','200'),
('HK4','XUYÊN MỸ','Phan Việt', 'HK4.jpg', '63000','63000','0','5','Nhã Nam','2020','Hồi ký/tự truyện','','Tiếng Việt','280','200'),
('HK5','BA MUỐN NUÔI CON BẰNG SỮA MẸ','Trình Tuấn', 'HK5.jpg','54000','54000','0','6','Nhã Nam','2020','Hồi ký/tự truyện','"Ít ra cuộc đời đã không lấy đi của ba tất cả, ba vẫn còn Ủn để nhớ, để thương, để quay về bình lặng sau cơn sóng dữ. Ủn là hạnh phúc của ba, là tất cả với ba bây giờ. Thật đáng sợ khi không còn gì bám víu trong lòng nước dữ, con người ta sẽ để mặc cho dòng đời cuốn đi. Ba sẽ thành kẻ đầu đường xó chợ, hay có thể là kẻ tâm thần ăn mày dĩ vãng, hay tệ hơn mà ai biết...Cảm ơn con đã níu ba lại để ba không gục ngã, để hôm nay nhận thấy tim mình còn thổn thức vì con."','Tiếng Việt','237','300');

INSERT INTO `products` (`PID`, `Title`, `Author`, `Image`, `MRP`, `Price`, `Discount`, `Available`, `Publisher`, `Edition`, `Category`, `Description`, `Language`, `page`, `weight`) VALUES
('HD1','RỄ TRỜI','Romain Gary', 'HD1.jpg','144000','144000','0','5','Nhã Nam','2020','Thế giới hiện đại','Lấy bối cảnh châu Phi sau chiến tranh thế giới lần thứ nhất, Rễ trời kể về thảm kịch của loài voi trên các xa van cũng như cuộc chiến của một “tay người Pháp” điên khùng, một kẻ muốn chuyển loài.','Tiếng Việt','624','200'),
('HD2','TIA LỬA','Matayoshi Naoki', 'HD2.jpg','59000','59000','0','6','Nhã Nam','2021','Thế giới hiện đại','Đêm pháo hoa, nghệ sĩ hài trẻ tuổi Tokunaga gặp người đàn anh Kamiya. Một Kamiya kỳ lạ, thất thường, không tuân theo bất cứ chuẩn mực nào khiến Tokunaga vừa bối rối vừa ngưỡng mộ. Cậu xin anh nhận mình làm đệ tử, bước theo anh trên con đường hướng tới lý tưởng thuần khiết. Nhưng rồi hiện thực cuộc sống nghiệt ngã giáng một đòn mạnh khiến Tokunaga choáng váng, và cậu buộc phải đưa ra lựa chọn…','Tiếng Việt','159','300'),
('HD3','CHUYỆN NGƯỜI TÙY NỮ (TB)','Margaret Atwood', 'HD3.jpg','100000','100000','0','7','Nhã Nam','2021','Thế giới hiện đại','Một thể chế thần quyền mọc lên trên cái nền nước Mỹ dân chủ vừa trải qua chính biến: Gilead, ngọn đèn trên quả đồi, quyết tâm đem ánh sáng của tem phiếu, của chuyên chế xã hội và của đạo đức Thanh giáo thế kỷ mười bảy cứu vãn thế giới đang chìm vào sa đọa, ô nhiễm môi trường và nạn vô sinh. Và tương lai của Gilead nằm trong tay các Tùy nữ như Offred: những cô gái mắn con được nuôi trong nhà các Quân trưởng, được chăm bẵm và o bế, chỉ cần mỗi tháng một lần nằm xuống làm bổn phận với quốc gia.','Tiếng Việt','407','250'),
('HD4','28','Jeong You- Jeong', 'HD4.jpg','123000','123000','0','5','Nhã Nam','2021','Thế giới hiện đại','','Tiếng Việt','488','340'),
('HD5','NẾU... THÌ','Randall Munroe', 'HD5.jpg','103000','103000','0','7','Nhã Nam','2021','Thế giới hiện đại','','Tiếng Việt','384','300');

INSERT INTO `products` (`PID`, `Title`, `Author`, `Image`, `MRP`, `Price`, `Discount`, `Available`, `Publisher`, `Edition`, `Category`, `Description`, `Language`, `page`, `weight`) VALUES
('NEW-1','RỄ TRỜI (tái bản 2022)','Romain Gary', 'NEW-1.jpg','144000','144000','0','5','Nhã Nam','2022','New','Lấy bối cảnh châu Phi sau chiến tranh thế giới lần thứ nhất, Rễ trời kể về thảm kịch của loài voi trên các xa van cũng như cuộc chiến của một “tay người Pháp” điên khùng, một kẻ muốn chuyển loài.','Tiếng Việt','624','200'),
('NEW-2','TIA LỬA (tái bản 2022)','Matayoshi Naoki', 'NEW-2.jpg','59000','59000','0','6','Nhã Nam','2022','New','Đêm pháo hoa, nghệ sĩ hài trẻ tuổi Tokunaga gặp người đàn anh Kamiya. Một Kamiya kỳ lạ, thất thường, không tuân theo bất cứ chuẩn mực nào khiến Tokunaga vừa bối rối vừa ngưỡng mộ. Cậu xin anh nhận mình làm đệ tử, bước theo anh trên con đường hướng tới lý tưởng thuần khiết. Nhưng rồi hiện thực cuộc sống nghiệt ngã giáng một đòn mạnh khiến Tokunaga choáng váng, và cậu buộc phải đưa ra lựa chọn…','Tiếng Việt','159','300'),
('NEW-3','CHUYỆN NGƯỜI TÙY NỮ (tái bản 2022)','Margaret Atwood', 'NEW-3.jpg','100000','100000','0','7','Nhã Nam','2022','New','Một thể chế thần quyền mọc lên trên cái nền nước Mỹ dân chủ vừa trải qua chính biến: Gilead, ngọn đèn trên quả đồi, quyết tâm đem ánh sáng của tem phiếu, của chuyên chế xã hội và của đạo đức Thanh giáo thế kỷ mười bảy cứu vãn thế giới đang chìm vào sa đọa, ô nhiễm môi trường và nạn vô sinh. Và tương lai của Gilead nằm trong tay các Tùy nữ như Offred: những cô gái mắn con được nuôi trong nhà các Quân trưởng, được chăm bẵm và o bế, chỉ cần mỗi tháng một lần nằm xuống làm bổn phận với quốc gia.','Tiếng Việt','407','250'),
('NEW-4','28 tái bản (2022)','Jeong You- Jeong', 'NEW-4.jpg','123000','123000','0','5','Nhã Nam','2022','New','','Tiếng Việt','488','340');




--
-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `UserName` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `Password` varchar(40) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;



INSERT INTO `users` (`UserName`, `Password`) VALUES
('test','test');

CREATE TABLE `admin` (
  `UserName` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `Password` varchar(40) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `admin` (`UserName`, `Password`) VALUES
('admin','admin');
--
-- Indexes for table `cart`
--
ALTER TABLE `cart`
  ADD PRIMARY KEY (`Customer`,`Product`),
  ADD KEY `Product` (`Product`);

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`PID`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`UserName`);
COMMIT;

ALTER TABLE `admin`
  ADD PRIMARY KEY (`UserName`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION;

